env:
  global:
    - CONAN_USERNAME: "monkeber"
    - CONAN_REFERENCE: "maxminddb/1.3.2"
    - CONAN_REMOTE: "monkeber"
    - CONAN_CHANNEL: "stable"
    - CONAN_GCC_VERSIONS: 8
    - CONAN_DOCKER_IMAGE: "lasote/conangcc8"

linux:
  os: linux
  sudo: required
  language: python
  python: "3.6"
  services:
    - docker

install:
  - python -m pip install --user --upgrade pip
  - pip install --user conan --upgrade
  - pip install --user conan_package_tools
  - conan user

script:
  python build.py
