env:
  global:
    - CONAN_REFERENCE: "maxminddb/1.3.2"
    - CONAN_REMOTE: "monkeber"
    - CONAN_CHANNEL: "stable"
    - CONAN_GCC_VERSIONS: 7

linux:
  os: linux
  sudo: required
  language: python
  python: "3.6"

install:
  - python -m pip install --user --upgrade pip
  - pip install --user conan --upgrade
  - pip install --user conan_package_tools
  - conan user

script:
  conan create . ${CONAN_REFERENCE}@${CONAN_REMOTE}/${CONAN_CHANNEL}
