env:
  global:
    - CONAN_REFERENCE: "maxminddb/1.3.2"
    - CONAN_REMOTE: "monkeber"
    - CONAN_CHANNEL: "stable"
    - CC_COMPILER: "gcc-8"
    - CXX_COMPILER: "g++-8"

linux:
  os: linux
  sudo: required
  language: python
  python: "3.6"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - gcc-8

install:
  - python -m pip install --user --upgrade pip
  - pip install --user conan --upgrade
  - pip install --user conan_package_tools
  - conan user

script:
  conan create . ${CONAN_REFERENCE}@${CONAN_REMOTE}/${CONAN_CHANNEL} -s compiler.version=8 -s compiler.libcxx=libstdc++11
